import type { Metadata, Viewport } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { getServerSession } from "next-auth"
import SessionProvider from "@/components/SessionProvider"
import clsx from "clsx";

import { Providers } from "./providers"
const inter = Inter({ subsets: ["latin"] })
// import '../lib/cron/cronJob';

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export const viewport: Viewport = {
    themeColor: [
        { media: "(prefers-color-scheme: light)", color: "white" },
        { media: "(prefers-color-scheme: dark)", color: "black" },
    ],
}

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    const session = await getServerSession()
    return (
        <html suppressHydrationWarning lang="en">
            <head />
            <body className={clsx("min-h-screen bg-background font-sans antialiased", inter.className)}>
                <Providers themeProps={{ attribute: "class", defaultTheme: "dark" }}>
                    <SessionProvider session={session}>{children}</SessionProvider>
                </Providers>
            </body>
        </html>
    )
}
