import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"

import { getServerSession } from "next-auth"
import SessionProvider from "./components/SessionProvider"

import {Providers} from "./providers";
const inter = Inter({ subsets: ["latin"] })
// import '../lib/cron/cronJob';

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    const session = await getServerSession()
    return (
        <html lang="en" >
            <body className={inter.className}>
                <Providers>
                    <SessionProvider session={session}>{children}</SessionProvider>
                </Providers>
            </body>
        </html>
    )
}
